# encrypt
# https://ci.appveyor.com/tools/encrypt
# validate
# https://ci.appveyor.com/tools/validate-yaml
# Build API
# https://www.appveyor.com/docs/build-worker-api

version: "{build}"
image: Visual Studio 2015

cache:
  - '%APPDATA%\npm-cache'
  - node_modules -> package.json
  - package-lock.json -> package.json

environment:
  CI_NAME: 'appveyor'
  NODEJS_VERSION: '10'
  NPM_TOKEN:
    secure: zTogpCh9AtlTR+osabCb9UMXMtIT8qTE0Rvay78bTORSysIVo5Ev+y6oOsHdDSO9
  GH_TOKEN:
    secure: wMVG1uvMB8qswngCrsL0eg6E/7HEaCjbAmXFM26V+sVO1OnP1/mgMu6kGX2uCWm0
  COVERALLS_REPO_TOKEN:
    secure: GVfYdXChXxEWFSfuXsHyGKcyAc97WrFQ17u4S07CtyOLTqB6z0Pb6ZmgHMgIfoKp

init:
  - git config --global core.autocrlf input

install:
  - ps: |
      Install-Product node $env:NODEJS_VERSION

      echo "the build worker image is $env:APPVEYOR_BUILD_WORKER_IMAGE"
      echo "the node version is $(node --version)"
      echo "the npm version is $(npm --version)"

      Add-AppveyorMessage "the build worker image is $env:APPVEYOR_BUILD_WORKER_IMAGE"
      Add-AppveyorMessage "the node version is $(node --version)"
      Add-AppveyorMessage "the npm version is $(npm --version)"

      $releaseVersion = $null

      # read release branch from package.json
      $releaseBranch = node -p "require('./package.json').branch"
      if (-not $releaseBranch) { $releaseBranch = "master" }

      # get last tag on the release branch
      git fetch --tags
      $lastTag = git tag -l --merged origin/master --sort=-taggerdate | Select-Object -Index 0  | %{$_ -replace "^v",""}
      if (-not $lastTag) { $lastTag = "$(node -p "require('./package.json').version")" }

      # parse the build message
      $test_message = "on $releaseBranch@$lastTag"
      if ($env:APPVEYOR_REPO_BRANCH -ne $releaseBranch) {
        $test_message = "base $test_message"
      }
      if ($env:APPVEYOR_PULL_REQUEST_NUMBER) {
        # build on request pull
        $test_message = "Develop Test for RP($env:APPVEYOR_PULL_REQUEST_NUMBER) $test_message"
      } elseif ($env:APPVEYOR_REPO_TAG_NAME) {
        # build on tag
        $test_message = "Release Test for $releaseBranch@$lastTag"
      } else {
        $test_message = "Develop Test $test_message"
        if ($env:APPVEYOR_REPO_BRANCH -eq $releaseBranch) {
          # current branch is the release branch
          # check the next release version
          $prereleaseLog = npx cross-env prerelease=true semantic-release -d
          echo $prereleaseLog
          if ($prereleaseLog -join "`n"  -match "The Next release version is ([^\r\n]+)")
          {
              $releaseVersion = $Matches[1]
              $test_message = "Release $releaseBranch@$releaseVersion <- $lastTag"
          }
        }
      }
      echo "$test_message"
      Update-AppveyorBuild -Version "$releaseBranch@$lastTag - $env:APPVEYOR_BUILD_NUMBER"
      Update-AppveyorBuild -Message "$test_message"
  - ps: Set-AppveyorBuildVariable 'TestVariable' 'This is a test message'
  - ps: Add-AppveyorMessage "Installing develop dependencies..."
  - ps: $timepoint = Get-Date
  - npm install -g coveralls
  - npm install
  - ps: Add-AppveyorMessage "Install develop dependencies use $($(New-TimeSpan $timepoint).TotalSeconds)s"

before_build:
  - ps: Add-AppveyorMessage "Compiling..."
  - ps: $timepoint = Get-Date

build_script:
  - npm run package

after_build:
  - ps: Add-AppveyorMessage "Compile use $($(New-TimeSpan $timepoint).TotalSeconds)s"

before_test:
  - ps: Add-AppveyorMessage "Running Tests..."
  - ps: $timepoint = Get-Date

test_script:
  - ps: Add-AppveyorMessage "Running Tests on Node$(node --version)..."
  - ps: $test_timepoint = Get-Date
  - npm run unit:node
  - ps: Add-AppveyorMessage "Run Tests on Node$(node --version) use $($(New-TimeSpan $test_timepoint).TotalSeconds)s"
  -
  - ps: Add-AppveyorMessage "Running Tests on IE8,IE9,Chrome by Karma..."
  - ps: $test_timepoint = Get-Date
  - npm run unit:browser -- --browsers IE8,IE9,Chrome --single-run
  - ps: Add-AppveyorMessage "Run Tests on IE8,IE9,Chrome by Karma use $($(New-TimeSpan $test_timepoint).TotalSeconds)s"
  -
  - ps: Add-AppveyorMessage "Running Tests on IE6,IE7 by Karma(no-iframe)..."
  - ps: $test_timepoint = Get-Date
  - npm run unit:browser -- --browsers IE6,IE7 --single-run --no-iframe
  - ps: Add-AppveyorMessage "Run Tests on IE6,IE7 by Karma(no-iframe) use $($(New-TimeSpan $test_timepoint).TotalSeconds)s"

after_test:
  - ps: Add-AppveyorMessage "Run Tests use $($(New-TimeSpan $timepoint).TotalSeconds)s"
  - ps: Add-AppveyorMessage "Uploading coverage by coveralls"
  - cat coverage/*/lcov.info | coveralls

deploy_script:
  - ps: |
      if ($releaseVersion) {
        Add-AppveyorMessage "Releasing $releaseBranch@$releaseVersion <- $lastTag..."
        $timepoint = Get-Date

        npx semantic-release

        $nextTag = git tag -l --merged origin/master --sort=-taggerdate | Select-Object -Index 0  | %{$_ -replace "^v",""}
        if ( $next_tag -ne $lastTag )
        {
          Add-AppveyorMessage "Released $releaseBranch@$releaseVersion <- $lastTag, use $($(New-TimeSpan $timepoint).TotalSeconds)s"
        } else {
          Add-AppveyorMessage "Release $releaseBranch@$releaseVersion failed" -Category Error
        }
      }
