branchs:
  -
    pattern: "^master$"
    channel: "latest"
  -
    pattern: "^([1-9][0-9]*)\\.(x|[1-9][0-9]*)\\.x$"
  -
    pattern: "^alpha$"
    channel: "alpha"
    prerelease: "alpha"

rules:
  -
    type: "feat"
    release: "patch"
    note: "Features"
  -
    type: "fix"
    release: "patch"
    note: "Bug Fixes"
  -
    type: "docs"
    release: "patch"
  -
    type: "build"
    release: ":scope"
